# Generated by Django 3.2.4 on 2021-06-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet_app', '0002_alter_tag_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
